# Site settings
title: Equivalent Exchange
email: gregvarias@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  On a journey to gain the skills to build beautiful and awesome things with code.
  Plenty of learning and adventure on the horizon!
baseurl: "/eqex" # the subpath of your site, e.g. /blog/
url: "http://gregrv.github.io" # the base hostname & protocol for your site
twitter_username: 180ad
github_username:  gregRV
timezone: America/California

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html

# SAVED FOR NOTES
# description: > # this means to ignore newlines until "baseurl:"
# #   Write an awesome description for your new site here. You can edit this
# #   line in _config.yml. It will appear in your document head meta (for
# #   Google search results) and in your feed.xml site description.